# Generated by Django 5.1.1 on 2024-11-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitthesis', '0014_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='sectionversion',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
