# Generated by Django 5.1.1 on 2024-11-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitthesis', '0015_alter_section_content_alter_sectionversion_content'),
        ('gitthesis', '0016_alter_section_content_alter_sectionversion_content'),
    ]

    operations = [
    ]
